packages:
  - "apps/*"
  - "packages/*"
  - "packages/*/*"
  - "!packages/*/dist"
  - "!packages/*/*/dist"
catalog:
  "@astrojs/starlight": "0.36.3"
  "@astrojs/starlight-tailwind": "4.0.2"
  "@dprint/formatter": "^0.5.1"
  "@dprint/typescript": "^0.95.15"
  "@effect-atom/atom": "0.5.0"
  "@effect/build-utils": "0.8.9"
  "@effect/cli": "0.73.2"
  "@effect/experimental": "0.58.0"
  "@effect/language-service": "0.56.0"
  "@effect/platform": "0.94.0"
  "@effect/platform-bun": "0.97.1"
  "@effect/platform-http": "0.91.1"
  "@effect/platform-node": "0.104.1"
  "@effect/vitest": "0.27.0"
  "@nx/js": "22.4.5"
  "@nx/node": "22.4.5"
  "@nx/react": "22.4.5"
  "@nx/vite": "22.4.5"
  "@nx/web": "22.4.5"
  "@solidjs/testing-library": "0.8.10"
  "@swc-node/register": "1.11.1"
  "@swc/core": "1.15.3"
  "@swc/helpers": "0.5.17"
  "@tailwindcss/postcss": "4.1.17"
  "@tailwindcss/typography": "0.5.19"
  "@tailwindcss/vite": "4.1.18"
  "@testing-library/dom": "10.4.1"
  "@testing-library/jest-dom": "6.9.1"
  "@testing-library/react": "16.3.0"
  "@types/node": "20.19.25"
  "@types/react": "19.2.7"
  "@types/react-dom": "19.2.3"
  "@types/validator": "13.15.10"
  "@vitejs/plugin-react": "5.1.1"
  "@vitejs/plugin-rsc": "0.5.1"
  "@vitest/ui": "4.0.9"
  astro: "5.17.1"
  autoprefixer: "10.4.22"
  class-variance-authority: "0.7.1"
  clsx: "2.1.1"
  dotenv: "^17.2.3"
  dprint: "0.51.1"
  effect: "3.19.16"
  globby: "16.0.0"
  husky: "9.1.7"
  jiti: "2.6.1"
  lint-staged: "16.2.7"
  lucide-react: "^0.554.0"
  lucide-solid: "^0.554.0"
  nx-oxlint: "0.1.1"
  oxlint: "0.15.15"
  postcss: "8.5.6"
  react: "19.2.0"
  react-dom: "19.2.0"
  sharp: "0.34.5"
  solid-js: "^1.9.9"
  starlight-sidebar-topics: "0.6.2"
  starlight-sidebar-topics-dropdown: "0.5.2"
  starlight-theme-nova: "0.10.0"
  tailwind-merge: "3.4.0"
  tailwindcss: "4.1.18"
  tailwindcss-animate: "1.0.7"
  tslib: "2.8.1"
  tsx: "4.20.6"
  tw-animate-css: "1.4.0"
  typescript: "5.9.3"
  validator: "13.15.23"
  verdaccio: "6.2.2"
  vite: "7.3.1"
  vite-plugin-devtools-json: "0.4.1"
  vite-plugin-lucide-preprocess: "1.4.6"
  vite-plugin-dts: "4.5.4"
  vite-plugin-solid: "^2.11.10"
  vite-tsconfig-paths: "5.1.4"
  vitest: "4.0.9"
  web-vitals: "5.1.0"
catalogMode: "prefer"
cleanupUnusedCatalogs: true
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - "better-sqlite3"
  - "core-js"
  - "esbuild"
  - "msgpackr-extract"
  - "nx"
