packages:
  - apps/*
  - packages/*
  - packages/*/*
  - '!packages/*/dist'
  - '!packages/*/*/dist'
  - '!packages/*/storybook-static'
  - '!packages/*/*/storybook-static'

catalog:
  '@ark-ui/react': ^4.9.2
  '@ark-ui/solid': ^4.10.2
  '@astrojs/react': ^4.4.2
  '@astrojs/solid-js': ^5.1.3
  '@astrojs/starlight': 0.36.3
  '@astrojs/starlight-tailwind': 4.0.2
  '@chromatic-com/storybook': ^5.0.1
  '@effect/cli': 0.73.2
  '@effect/language-service': 0.56.0
  '@effect/platform': 0.94.0
  '@effect/platform-node': 0.104.1
  '@effect/vitest': 0.27.0
  '@nx/js': 22.4.5
  '@nx/node': 22.4.5
  '@nx/react': 22.4.5
  '@nx/storybook': 22.4.5
  '@nx/vite': 22.4.5
  '@nx/web': 22.4.5
  '@solidjs/testing-library': 0.8.10
  '@storybook/addon-a11y': ^10.2.8
  '@storybook/addon-docs': ^10.2.8
  '@storybook/addon-postcss': ^2.0.0
  '@storybook/addon-vitest': ^10.2.8
  '@storybook/react': ^10.2.8
  '@storybook/react-vite': ^10.2.8
  '@swc-node/register': 1.11.1
  '@swc/core': 1.15.3
  '@swc/helpers': 0.5.17
  '@tabler/icons-solidjs': ^3.36.1
  '@tailwindcss/vite': 4.1.18
  '@types/node': 20.19.25
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-react': 5.1.1
  '@vitest/browser-playwright': ^4.0.18
  '@vitest/ui': ^4.0.9
  astro: 5.17.1
  astro-expressive-code: 0.41.6
  autoprefixer: 10.4.22
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  dprint: 0.51.1
  effect: 3.19.16
  glob: ^11.0.0
  globals: ^16.5.0
  husky: 9.1.7
  jiti: 2.6.1
  jsdom: ^26.0.0
  lint-staged: 16.2.7
  lucide-react: ^0.554.0
  lucide-solid: ^0.554.0
  nx-oxlint: 0.1.1
  postcss: 8.5.6
  react: 19.2.4
  react-dom: 19.2.4
  react-router: ^7.1.5
  react-use-measure: ^2.1.1
  recharts: ^2.15.1
  shadcn: ^2.10.0
  sharp: 0.34.5
  solid-devtools: ^0.34.3
  solid-js: ^1.9.9
  sonner: ^1.7.4
  starlight-sidebar-topics: 0.6.2
  starlight-sidebar-topics-dropdown: 0.5.2
  starlight-theme-nova: 0.10.0
  storybook: ^10.2.8
  storybook-solidjs-vite: ^10.0.9
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  ts-patch: ^3.2.1
  tslib: 2.8.1
  tw-animate-css: 1.4.0
  typescript: 5.9.3
  vite: 7.3.1
  vite-plugin-dts: 4.5.4
  vite-plugin-solid: ^2.11.10
  vite-tsconfig-paths: ^6.1.1
  vitest: ^4.0.18

catalogMode: prefer

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - esbuild
  - msgpackr-extract
  - nx
